export const NAVAL_UNIT_DATA = {
  gunboat: {
    name: 'Gunboat',
    cost: 500,
    buildTime: 5000,
    health: 200,
    speed: 70,
    damage: 15,
    range: 250,
    attackCooldown: 800,
    radius: 15,
    vision: 350,
    movementType: 'water' as const,
  },
  submarine: {
    name: 'Submarine',
    cost: 950,
    buildTime: 9500,
    health: 120,
    speed: 50,
    damage: 80,
    range: 300,
    attackCooldown: 3000,
    radius: 12,
    vision: 300,
    movementType: 'water' as const,
  },
  destroyer: {
    name: 'Destroyer',
    cost: 1000,
    buildTime: 10000,
    health: 400,
    speed: 60,
    damage: 30,
    range: 280,
    attackCooldown: 1200,
    radius: 20,
    vision: 400, // Important: destroyers can detect subs
    movementType: 'water' as const,
  },
  transport: {
    name: 'Amphibious Transport',
    cost: 700,
    buildTime: 7000,
    health: 300,
    speed: 60,
    damage: 0,
    range: 0,
    attackCooldown: 0,
    radius: 18,
    vision: 250,
    movementType: 'amphibious' as const,
    capacity: 5,
  }
};
